# Generated by Django 5.2.3 on 2025-06-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_polisi', models.CharField(max_length=15, unique=True)),
                ('merek', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('jenis', models.CharField(choices=[('mobil', 'Mobil'), ('motor', 'Motor')], default='mobil', max_length=10)),
                ('status', models.CharField(choices=[('terparkir', 'Terparkir'), ('keluar', 'Keluar'), ('perawatan', 'Dalam Perawatan')], default='terparkir', max_length=15)),
                ('waktu_masuk', models.DateTimeField(auto_now_add=True)),
                ('waktu_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'garasi_kendaraan',
            },
        ),
    ]
